production:
  adapter: postgresql
  database: dd0dfvfu5poqkt
  host: ec2-54-163-230-198.compute-1.amazonaws.com
  pool: 20
  timeout: 5000
  username: oacvbsacdhcslw
  password: cea98fbb1e36356410cb9e3235c0a6c47021f720958feb88636825f3ab6647d7

development:
  adapter: postgresql
  encoding: unicode
  database: food_order_management
  pool: 5
